name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-matrix:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}
      - name: Prepare artifact
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/ugh artifacts/ugh-${{ matrix.target }}
          cd artifacts
          tar -czf ugh-${{ matrix.target }}.tar.gz ugh-${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ugh-${{ matrix.target }}
          path: artifacts/ugh-${{ matrix.target }}.tar.gz

  publish:
    name: Publish Release
    needs: build-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create release notes
        id: notes
        uses: ncipollo/release-notes@v1
        with:
          configuration: |
            {
              "commitTemplate": "- {{message}} ({{sha}})"
            }
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.notes.outputs.release_notes }}
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
